### ISSUE TITLE
Return information in error if fail to parse CSV.

### ISSUE THREAD

**Issue by CrowdHailer** [bcpeinhardt/gsv#3]
I think this could be built in two parts.

First do the simplest thing using the information that is easy to get. I.e. Expected a closing quote but got line ended. 

Second (maybe this should be a second issue, but it's probably only worth discussing after the first is done) Add line and column information to errors

**Comment by bcpeinhardt** [comment]
There are now functions called `to_lists_or_panic` and `to_lists_or_error` whose error message includes the offending line and column within the csv :)
I don't like the current api, but the functionality is there now if you need it.
