### ISSUE TITLE
Function for parsing to dicts

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/gsv#9]
Hello!

I think it could be useful to have a function for parsing to a list of dictionaries rather than to a list of lists. This would lose the ordering, but it would enable the programmer to use `dict.get` for each row.

```csv
Name,Score
Lucy,15
Samsara,13
Dave,
```
```gleam
[
  dict.from_list([#("Name", "Lucy"), #("Score", "15")]),
  dict.from_list([#("Name", "Samsara"), #("Score", "13")]),
  dict.from_list([#("Name", "Dave"), #("Score", "")]),
]
```

Here's an example of me doing roughly this

https://github.com/lpil/gliberapay/blob/4a1f74f933a063e1b11233e674fe7052023a5ad2/src/gliberapay.gleam#L68-L89

Thank you

**Comment by bcpeinhardt** [comment]
v2 published
